import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../components/Header";
import SideNav from "../components/SideNav";
import { Col, Row } from "react-bootstrap";
import PageContainer from "../components/PageContainer";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
      </Head>
      <PageContainer>
        <Component {...pageProps} />
      </PageContainer>
    </>
  );
}

export default MyApp;
